struct States {
    static let Alabama = (id: 0, name: "Alabama", abbreviation: "AL")
    static let Alaska = (id: 1, name: "Alaska", abbreviation: "AK")
    static let Arizona = (id: 2, name: "Arizona", abbreviation: "AZ")
    static let Arkansas = (id: 3, name: "Arkansas", abbreviation: "AR")
    static let California = (id: 4, name: "California", abbreviation: "CA")
    static let Colorado = (id: 5, name: "Colorado", abbreviation: "CO")
    static let Connecticut = (id: 6, name: "Connecticut", abbreviation: "CT")
    static let Delaware = (id: 7, name: "Delaware", abbreviation: "DE")
    static let DistrictOfColumbia = (id: 8, name: "District Of Columbia", abbreviation: "DC")
    static let Florida = (id: 9, name: "Florida", abbreviation: "FL")
    static let Georgia = (id: 10, name: "Georgia", abbreviation: "GA")
    static let Hawaii = (id: 11, name: "Hawaii", abbreviation: "HI")
    static let Idaho = (id: 12, name: "Idaho", abbreviation: "ID")
    static let Illinois = (id: 13, name: "Illinois", abbreviation: "IL")
    static let Indianna = (id: 14, name: "Indianna", abbreviation: "IN")
    static let Iowa = (id: 15, name: "Iowa", abbreviation: "IA")
    static let Kansas = (id: 16, name: "Kansas", abbreviation: "KS")
    static let Kentucky = (id: 17, name: "Kentucky", abbreviation: "KY")
    static let Louisiana = (id: 18, name: "Louisiana", abbreviation: "LA")
    static let Maine = (id: 19, name: "Maine", abbreviation: "ME")
    static let Maryland = (id: 20, name: "Maryland", abbreviation: "MD")
    static let Massachusetts = (id: 21, name: "Massachusetts", abbreviation: "MA")
    static let Michigan = (id: 22, name: "Michigan", abbreviation: "MI")
    static let Minnesota = (id: 23, name: "Minnesota", abbreviation: "MN")
    static let Mississippi = (id: 24, name: "Mississippi", abbreviation: "MS")
    static let Missouri = (id: 25, name: "Missouri", abbreviation: "MO")
    static let Montana = (id: 26, name: "Montana", abbreviation: "MT")
    static let Nebraska = (id: 27, name: "Nebraska", abbreviation: "NE")
    static let Nevada = (id: 28, name: "Nevada", abbreviation: "NV")
    static let NewHampshire = (id: 29, name: "New Hampshire", abbreviation: "NH")
    static let NewJersey = (id: 30, name: "New Jersey", abbreviation: "NJ")
    static let NewMexico = (id: 31, name: "New Mexico", abbreviation: "NM")
    static let NewYork = (id: 32, name: "New York", abbreviation: "NY")
    static let NorthCarolina = (id: 33, name: "North Carolina", abbreviation: "NC")
    static let NorthDakota = (id: 34, name: "North Dakota", abbreviation: "ND")
    static let Ohio = (id: 35, name: "Ohio", abbreviation: "OH")
    static let Oklahoma = (id: 36, name: "Oklahoma", abbreviation: "OK")
    static let Oregon = (id: 37, name: "Oregon", abbreviation: "OR")
    static let Pennsylvania = (id: 38, name: "Pennsylvania", abbreviation: "PA")
    static let PuertoRico = (id: 39, name: "Puerto Rico", abbreviation: "PR")
    static let RhodeIsland = (id: 40, name: "Rhode Island", abbreviation: "RI")
    static let SouthCarolina = (id: 41, name: "South Carolina", abbreviation: "SC")
    static let SouthDakota = (id: 42, name: "South Dakota", abbreviation: "SD")
    static let Tennessee = (id: 43, name: "Tennessee", abbreviation: "TN")
    static let Texas = (id: 44, name: "Texas", abbreviation: "TX")
    static let Utah = (id: 45, name: "Utah", abbreviation: "UT")
    static let Vermont = (id: 46, name: "Vermont", abbreviation: "VT")
    static let Virginia = (id: 47, name: "Virginia", abbreviation: "VA")
    static let Washington = (id: 48, name: "Washington", abbreviation: "WA")
    static let WestVirginia = (id: 49, name: "West Virginia", abbreviation: "WV")
    static let Wisconsin = (id: 50, name: "Wisconsin", abbreviation: "WI")
    static let Wyoming = (id: 51, name: "Wyoming", abbreviation: "WY")
    
    static let all = [ Alabama, Alaska, Arizona, Arkansas, California, Colorado, Connecticut, Delaware, DistrictOfColumbia, Florida, Georgia, Hawaii, Idaho, Illinois, Indianna, Iowa, Kansas, Kentucky, Louisiana, Maine, Maryland, Massachusetts, Michigan, Minnesota, Mississippi, Missouri, Montana, Nebraska, Nevada, NewHampshire, NewJersey, NewMexico, NewYork, NorthCarolina, NorthDakota, Ohio, Oklahoma, Oregon, Pennsylvania, PuertoRico, RhodeIsland, SouthCarolina, SouthDakota, Tennessee, Texas, Utah, Vermont, Virginia, Washington, WestVirginia, Wisconsin, Wyoming ]
}


